### PR TITLE
Checks if there has already been a response from a bot.

### PR DESCRIPTION
**Pull request by kanyetjk**
Currently only checks for a comment with "Beep boop"

### CODE REVIEW

**Review by joshuapinto470 — COMMENTED** [review]
Maby even check if "bot" is in username

**Review by Sentdex — APPROVED** [review]
Haha, that seems good enough! Thank you!

**Review by Sentdex — CHANGES_REQUESTED** [review]
O, I didn't notice the conficts. 

I am guessing you cloned this prior to another PR that was accepted. Looks like it was mostly the debug mode that should be included.

I can't merge until that's done.

**Comment by kanyetjk** [comment]
Should workout fine now

**Comment by Sentdex** [comment]
Awesome, thank you!

**Pull request merged**
